ensure correct stack is used

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -132,6 +132,19 @@ if [ -z "${STACK}" ]; then
   STACK="cedar-14"
 fi
 
+# ensure correct stack
+if [[ ! "$STACK" == "cedar-14" ]]; then
+
+  echo
+  echo "-----> ERROR: This version of the buildpack is intended for use with the 'cedar-14' stack"
+  echo
+  echo "       Use the 'heroku stack:set' CLI command to use the 'cedar-14' stack."
+  echo "       See https://devcenter.heroku.com/articles/stack for more information."
+  echo
+  exit 1
+
+fi
+
 # read in R version if file exists
 if [[ -f "$BUILD_DIR/.r-version" ]]; then
   R_VERSION=`read_var $BUILD_DIR/.r-version`
